create table mdr.BPM_TASKDEF (
    ID VARCHAR2(36) NOT NULL,
    NAME VARCHAR(120) NOT NULL
);
ALTER TABLE mdr.BPM_TASKDEF ADD CONSTRAINT PK1_BPM_TASKDEF PRIMARY KEY (ID);

create table mdr.BPM_TASKSTATE (
    ID INT NOT NULL,
    NAME VARCHAR (60) NOT NULL
);
ALTER TABLE mdr.BPM_TASKSTATE ADD CONSTRAINT PK1_BPM_TASKSTATE PRIMARY KEY (ID);

-- DEFAULT STATE
insert into mdr.BPM_TASKSTATE (ID, NAME) values (1,'Created');
insert into mdr.BPM_TASKSTATE (ID, NAME) values (2,'Ready');
insert into mdr.BPM_TASKSTATE (ID, NAME) values (3,'Reserved');
insert into mdr.BPM_TASKSTATE (ID, NAME) values (4,'Suspended');
insert into mdr.BPM_TASKSTATE (ID, NAME) values (5,'InProgress');
insert into mdr.BPM_TASKSTATE (ID, NAME) values (6,'Failed');
insert into mdr.BPM_TASKSTATE (ID, NAME) values (7,'Error');
insert into mdr.BPM_TASKSTATE (ID, NAME) values (8,'Exited');
insert into mdr.BPM_TASKSTATE (ID, NAME) values (9,'Obsolete');
create table mdr.BPM_TASK (
    ID VARCHAR2(36) NOT NULL,
    TASKDEF_ID VARCHAR2(36) NOT NULL,
    DATA VARCHAR(2000) NULL,
    ERROR VARCHAR(2000) NULL,
    ASSIGNEE VARCHAR2(36) NULL
);
ALTER TABLE mdr.BPM_TASK ADD CONSTRAINT PK1_BPM_TASK PRIMARY KEY (ID);
ALTER TABLE mdr.BPM_TASK ADD CONSTRAINT FK1_BPM_TASK FOREIGN KEY (TASKDEF_ID) 
    REFERENCES mdr.BPM_TASKDEF (ID);

create table mdr.BPM_TASKSTATUS(
    TASK_ID VARCHAR2(36) NOT NULL,
    TASKSTATE_ID INT NOT NULL,
    FROMDATE TIMESTAMP NOT NULL,
    USER_ID VARCHAR(36) NOT NULL,
    THRUDATE TIMESTAMP NULL
);
ALTER TABLE mdr.BPM_TASKSTATUS ADD CONSTRAINT PK1_BPM_TASKSTATUS PRIMARY KEY (TASK_ID,TASKSTATE_ID,FROMDATE);